GET http://localhost:3000/universities

###

GET http://localhost:3000/universities/622a73770389b59ed3f9459a

###

POST http://localhost:3000/universities
Content-Type: application/json

{
    "alpha_two_code": "BR",
        "web_pages": "www.pucrio.br",
        "name": "PUC-RIO",
        "country": "Brasil",
        "domains": "puc.br",
        "state_province": "RJ"
}

###


DELETE http://localhost:3000/universities/622a740bf6865bb719a4d5a5

###

PATCH  http://localhost:3000/universities/622a740bf6865bb719a4d5a5
Content-Type: application/json

{
    "name": "UFRJ"
}